spring.application.name=SpringBackend


# GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23lifLYWyFn76266yl
spring.security.oauth2.client.registration.github.client-secret=8cb245c550396ab15a4555fb29fd4917e6254d0f
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Google Login

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=


logging.level.org.springframework.security=TRACE