apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
images:
  - name: 729231827726.dkr.ecr.us-east-2.amazonaws.com/dev/voyago
    newTag: backend-27deb8df9716d33eb60ab0268c66e2659a6de261
