apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
images:
  - name: 729231827726.dkr.ecr.us-east-2.amazonaws.com/dev/voyago
    newTag: backend-daeeeaba9d96266b9cdefb6cbc7ff3c081fe1ce7
